# Generated by Django 4.1.5 on 2023-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20200926_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meal',
            field=models.CharField(choices=[('صبحانه', 'صبحانه'), ('نهار', 'نهار'), ('شام', 'شام')], default='صبحانه', max_length=50),
        ),
    ]
